 # DataFrame
 #### DateFrame = Collections of Series. E.g: 2,3 Series(Horizontal) in a signle box

In [2]:
import numpy as np
import pandas as pd

#### Creating a Dataframe

In [3]:
# DataFrame From Dictionary.
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [4]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
# DataFrame From List
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [6]:
columns = [ "Name" , "Age" , "City" , "Salary" ]
df2 = pd.DataFrame(data_list, columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selection And Indexing of Columns

In [7]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
df2['Name']                 # Instead of 0,1...columns name, their actual columns names will be used.

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [9]:
df2["City"]

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [10]:
df2[ [ "Name" , "City" ] ]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

#### Creating a new Column

In [11]:
df2["Designation"] = [ "Doctor" , "Eng" , "Doctor" , "Eng" ]

In [12]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000         Eng

#### Removing Columns

In [13]:
df2.drop("Designation", axis = 1)       # BY default axis = 0 -> row, so df2.drop("Designation") -> Error , because "Designaion"  is at axis = 1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [14]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000         Eng

In [15]:
# As After removing the "Desiignation" column, it is still showing in df2 , 
# so we will use keyword inplace.
df2.drop("Designation", axis = 1, inplace= True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [16]:
df2.drop([ "City" , "Salary" ] , axis = 1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [17]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
df2.drop(0, axis = 0 )

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

#### Selecting Rows

In [20]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
# loc() ->location , used for selecting rows.
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [25]:
df2.loc[ [ 0 , 1 ] ]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [26]:
# iloc = index location -> also used for rows.
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

#### Selecting Subsets of Rows and Columns

In [32]:
df.loc[[0,1]][["City" , "Salary"]]             # df.loc[[0,1]] = select subset of rows then [["City" , "Salary"]] is used for columns.

       City  Salary
0  New York   65000
1     Paris   70000

In [33]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [34]:
df.loc[[2,3]][["City","Salary"]]

     City  Salary
2  Berlin   62000
3  London   85000

#### Conditional Selection:

In [35]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [36]:
# People whose age is above 30.
df2[ df2["Age"] > 30 ]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [38]:
 # People whose age is above 30 and belongs to Paris.
df2[ (df2["Age"] > 30) & (df2["City"] == "Paris") ]

   Name  Age   City  Salary
1  Anna   34  Paris   70000